spring:
  application:
    name: config-service

  cloud:
    config:
      label: main
      server:
        git:
          uri: ${SERVER_GIT_URI}
          default-label: main

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    config:
      enabled: false